version: '2.1'
services:
  elasticsearch:
    image: "iskelazzz/co.empathy.academy.indexedelastic:lastest"
    hostname: "elasticsearch"
    container_name: es-imdb
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  searchapi:
    container_name: searchIMDb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch